name: "Symbiote"

on:
  workflow_dispatch:
    inputs:
      stateId:
        description: "State Id"
      eventName:
        description: "Event Name"
      eventPayload:
        description: "Event Payload"
      settings:
        description: "Settings"
      authToken:
        description: "Auth Token"
      ref:
        description: "Ref"
      signature:
        description: "The kernel signature"
      command:
        description: "Command"

jobs:
  compute:
    name: "Symbiote"
    runs-on: ubuntu-latest
    permissions: write-all
    environment: ${{ github.ref == 'refs/heads/main' && 'main' || 'development' }}
    env:
      KERNEL_PUBLIC_KEY: ${{ secrets.KERNEL_PUBLIC_KEY }}
      PLUGIN_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      LOG_LEVEL: ${{ secrets.LOG_LEVEL }}
      DENO_KV_UUID: ${{ secrets.DENO_KV_UUID }}
      DENO_KV_ACCESS_TOKEN: ${{ secrets.DENO_DEPLOY_TOKEN }}
      AI_API_KEY: ${{ secrets.AI_API_KEY }}
      OAUTH: ${{ secrets.OAUTH }}
      TELEGRAM: ${{ secrets.TELEGRAM }}
      SYMBIOTE_HOST: ${{ secrets.SYMBIOTE_HOST }}
      WORKER: ${{ secrets.WORKER }}

    steps:
      - uses: actions/checkout@v4

      - run: ${{ toJSON(inputs) }}
        shell: cat {0}

      - name: Execute directive
        uses: ./
        env:
          NODE_ENV: ${{ secrets.NODE_ENV }}
          GITHUB_RUN_ID: ${{ github.run_id }}
          APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
          APP_ID: ${{ secrets.APP_ID }}
          KERNEL_PUBLIC_KEY: ${{ secrets.KERNEL_PUBLIC_KEY }}
          AI_API_KEY: ${{ secrets.AI_API_KEY }}
          PLUGIN_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DENO_KV_UUID: ${{ secrets.DENO_KV_UUID }}
          DENO_KV_ACCESS_TOKEN: ${{ secrets.DENO_DEPLOY_TOKEN }}
          SYMBIOTE_HOST: ${{ secrets.SYMBIOTE_HOST }}
          WORKER: ${{ secrets.WORKER }}
          OAUTH: ${{ secrets.OAUTH }}
          TELEGRAM: ${{ secrets.TELEGRAM }}
